apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - image: rlamana/example-react
        name: movies